INSERT INTO OnlineOrder(ItemDescription, WebSite, Price, Status_OrderStatusId)
VALUES('Sharon DUMMY item' ,'yad 2',54, 3)
INSERT INTO OnlineOrder(ItemDescription, WebSite, Price, Status_OrderStatusId)
VALUES('Sharon DUMMY item' ,'yad 2',54, 3)
INSERT INTO OnlineOrder(ItemDescription, WebSite, Price, Status_OrderStatusId)
VALUES('Sharon DUMMY item' ,'yad 2',54, 3);
INSERT INTO OnlineOrder(ItemDescription, WebSite, Price, Status_OrderStatusId)
VALUES('Sharon DUMMY item' ,'yad 2',54, 3);
INSERT INTO OnlineOrder(ItemDescription, WebSite, Price, Status_OrderStatusId)
VALUES('Sharon DUMMY item' ,'yad 2',54, 3);
INSERT INTO OnlineOrder(ItemDescription, WebSite, Price, Status_OrderStatusId)
VALUES('Sharon DUMMY item' ,'yad 2',54, 3);
INSERT INTO OnlineOrder(ItemDescription, WebSite, Price, Status_OrderStatusId)
VALUES('Sharon DUMMY item' ,'yad 2',54, 3);
INSERT INTO OnlineOrder(ItemDescription, WebSite, Price, Status_OrderStatusId)
VALUES('Sharon DUMMY item' ,'yad 2',54, 3);
INSERT INTO OnlineOrder(ItemDescription, WebSite, Price, Status_OrderStatusId)
VALUES('Sharon DUMMY item' ,'yad 2',54, 3);
INSERT INTO OnlineOrder(ItemDescription, WebSite, Price, Status_OrderStatusId) 
VALUES('Sharon DUMMY item' ,'yad 2',54, 3);